# Generated by Django 3.1.7 on 2022-12-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisLikesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dislike_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InterestsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interested_in', models.CharField(max_length=100)),
                ('not_interested_in', models.CharField(max_length=100)),
                ('hobbies', models.CharField(max_length=200)),
                ('profile_url', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LikesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
